### ISSUE TITLE
Required property activity is missing from Event.

### ISSUE THREAD

**Issue by thill-odi** [participant-co-uk/OpenActive#1]
In the Events feed, none of the Events have an `activity` field, as is required by the spec. 

This isn't just an arbitrary requirement. Without indicating the activity, it's hard for end-users to know what the event actually is!

**Comment by nickevansuk** [comment]
(see https://developer.openactive.io/publishing-data/activity-list-references)

**Comment by nickevansuk** [comment]
This appears to have been resolved
