### ISSUE TITLE
Problems with Event Schedules

### ISSUE THREAD

**Issue by thill-odi** [participant-co-uk/OpenActive#2]
There are a couple of missing attributes in the Event feeds' `Schedule`s. Specifically:

`scheduleTimezone` isn't indicated (presumably "Europe/London" would be the correct value).

There's no frequency indication. This could be `byDay`, `byMonth`, `byMonthDay`, or `repeatFrequency`. See further https://schema.org/Schedule or https://www.openactive.io/modelling-opportunity-data/EditorsDraft/#publishing-event-schedules for how this works.

**Comment by thill-odi** [comment]
Sorry - just realised you can fix the first of these by changing `beta:timeZone` to `scheduleTimezone`.

**Comment by nickevansuk** [comment]
This appears to have been resolved
